#pragma once

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/i2s_std.h"
#include "driver/ledc.h"
#include "driver/spi_master.h"

#define HARDWARE_BOARD_TYPE                     "esp32s3_tirtc_monitor"

#define HARDWARE_BOARD_I2C_NUM                  I2C_NUM_0
#define HARDWARE_BOARD_I2C_SDA                  GPIO_NUM_1
#define HARDWARE_BOARD_I2C_SCL                  GPIO_NUM_2
#define HARDWARE_BOARD_I2C_FREQ_HZ              100000

#define HARDWARE_BOARD_PCA9557_ADDRESS          0x19
#define HARDWARE_BOARD_LCD_CS_GPIO_MASK         (1U << 0)
#define HARDWARE_BOARD_PA_EN_GPIO_MASK          (1U << 1)
#define HARDWARE_BOARD_CAMERA_PWDN_GPIO_MASK    (1U << 2)
#define HARDWARE_BOARD_IO_EXPANDER_OUTPUT_INIT  0x05

#define HARDWARE_BOARD_LCD_SPI_HOST             SPI3_HOST
#define HARDWARE_BOARD_LCD_PIXEL_CLOCK_HZ       (80 * 1000 * 1000)
#define HARDWARE_BOARD_LCD_CMD_BITS             8
#define HARDWARE_BOARD_LCD_PARAM_BITS           8
#define HARDWARE_BOARD_LCD_BITS_PER_PIXEL       16
#define HARDWARE_BOARD_LCD_WIDTH                320
#define HARDWARE_BOARD_LCD_HEIGHT               240
#define HARDWARE_BOARD_LCD_DRAW_BUF_HEIGHT      10
#define HARDWARE_BOARD_LCD_SPI_MOSI             GPIO_NUM_40
#define HARDWARE_BOARD_LCD_SPI_CLK              GPIO_NUM_41
#define HARDWARE_BOARD_LCD_SPI_CS               GPIO_NUM_NC
#define HARDWARE_BOARD_LCD_DC                   GPIO_NUM_39
#define HARDWARE_BOARD_LCD_RST                  GPIO_NUM_NC
#define HARDWARE_BOARD_LCD_BACKLIGHT            GPIO_NUM_42
#define HARDWARE_BOARD_LCD_BACKLIGHT_LEDC_TIMER LEDC_TIMER_0
#define HARDWARE_BOARD_LCD_BACKLIGHT_LEDC_CHANNEL LEDC_CHANNEL_0

#define HARDWARE_BOARD_AUDIO_I2S_PORT           I2S_NUM_0
#define HARDWARE_BOARD_AUDIO_LRCK               GPIO_NUM_13
#define HARDWARE_BOARD_AUDIO_MCLK               GPIO_NUM_38
#define HARDWARE_BOARD_AUDIO_BCLK               GPIO_NUM_14
#define HARDWARE_BOARD_AUDIO_DIN                GPIO_NUM_12
#define HARDWARE_BOARD_AUDIO_DOUT               GPIO_NUM_45
#define HARDWARE_BOARD_AUDIO_PA_GPIO            GPIO_NUM_NC
#define HARDWARE_BOARD_AUDIO_ES7210_ADDR        0x82
#define HARDWARE_BOARD_AUDIO_SAMPLE_RATE_HZ     16000
#define HARDWARE_BOARD_AUDIO_BITS_PER_SAMPLE    16
#define HARDWARE_BOARD_AUDIO_CHANNELS           2
#define HARDWARE_BOARD_AUDIO_ADC_CHANNELS       2
#define HARDWARE_BOARD_AUDIO_ADC_TDM_CHANNELS   4
#define HARDWARE_BOARD_AUDIO_ADC_CHANNEL_MASK   0x03
#define HARDWARE_BOARD_AUDIO_ADC_PRIMARY_CHANNEL 0
#define HARDWARE_BOARD_AUDIO_ADC_REFERENCE_ENABLED 1
/*
 * The board routes near-end speech to ES7210 MIC1 and the ES8311 speaker
 * loopback to physical MIC3. ES7210 serializes those inputs as
 * MIC1, MIC3, MIC2, MIC4, so the required TDM slots are 0 and 1. Gain masks
 * still use physical microphone numbering, where MIC3 is channel 2. Keep the
 * wire slot, packed DMA channel, and physical codec channel explicit because
 * they intentionally use different indexes.
 */
#define HARDWARE_BOARD_AUDIO_ADC_REFERENCE_TDM_SLOT 1
#define HARDWARE_BOARD_AUDIO_ADC_REFERENCE_DMA_CHANNEL 1
#define HARDWARE_BOARD_AUDIO_ADC_REFERENCE_CODEC_CHANNEL 2
#define HARDWARE_BOARD_AUDIO_ADC_REFERENCE_GAIN_DB 0.0f
#define HARDWARE_BOARD_AUDIO_ADC_REFERENCE_DIGITAL_GAIN_Q8 256U
#define HARDWARE_BOARD_AUDIO_ADC_CODEC_CHANNELS 4
#define HARDWARE_BOARD_AUDIO_DEFAULT_VOLUME     100
#define HARDWARE_BOARD_AUDIO_DEFAULT_ADC_GAIN_DB 24.0f

#define HARDWARE_BOARD_CAMERA_ENABLED           1
#define HARDWARE_BOARD_CAMERA_PWDN              GPIO_NUM_NC
#define HARDWARE_BOARD_CAMERA_RESET             GPIO_NUM_NC
#define HARDWARE_BOARD_CAMERA_XCLK              GPIO_NUM_5
/* GPIO1/GPIO2 are already owned by the board I2C bus; GPIO_NUM_NC means reuse I2C0 for SCCB SDA. */
#define HARDWARE_BOARD_CAMERA_SIOD              GPIO_NUM_NC
#define HARDWARE_BOARD_CAMERA_SIOC              GPIO_NUM_2
#define HARDWARE_BOARD_CAMERA_D0                GPIO_NUM_16
#define HARDWARE_BOARD_CAMERA_D1                GPIO_NUM_18
#define HARDWARE_BOARD_CAMERA_D2                GPIO_NUM_8
#define HARDWARE_BOARD_CAMERA_D3                GPIO_NUM_17
#define HARDWARE_BOARD_CAMERA_D4                GPIO_NUM_15
#define HARDWARE_BOARD_CAMERA_D5                GPIO_NUM_6
#define HARDWARE_BOARD_CAMERA_D6                GPIO_NUM_4
#define HARDWARE_BOARD_CAMERA_D7                GPIO_NUM_9
#define HARDWARE_BOARD_CAMERA_VSYNC             GPIO_NUM_3
#define HARDWARE_BOARD_CAMERA_HREF              GPIO_NUM_46
#define HARDWARE_BOARD_CAMERA_PCLK              GPIO_NUM_7
#define HARDWARE_BOARD_CAMERA_XCLK_FREQ_HZ      (24 * 1000 * 1000)
#define HARDWARE_BOARD_CAMERA_FB_COUNT          1
#define HARDWARE_BOARD_CAMERA_HMIRROR           0
#define HARDWARE_BOARD_CAMERA_VFLIP             0
#define HARDWARE_BOARD_CAMERA_XCLK_LEDC_TIMER   LEDC_TIMER_1
#define HARDWARE_BOARD_CAMERA_XCLK_LEDC_CHANNEL LEDC_CHANNEL_1
