#pragma once

#include "app_config.h"

#ifndef APP_CONFIG_WECHAT_VOIP_ENABLE
#define APP_CONFIG_WECHAT_VOIP_ENABLE 1
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE
#define APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE APP_CONFIG_DEVICE_BINDING_API_BASE
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_API_BASE
#define APP_CONFIG_WECHAT_VOIP_API_BASE APP_CONFIG_DEVICE_BINDING_API_BASE
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_MQTT_URI
#define APP_CONFIG_WECHAT_VOIP_MQTT_URI APP_CONFIG_DEVICE_BINDING_MQTT_URI
#endif

#define WECHAT_VOIP_VERSION_RELEASE     0
#define WECHAT_VOIP_VERSION_DEVELOPMENT 1
#define WECHAT_VOIP_VERSION_TRIAL       2

#ifndef APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE
#define APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE WECHAT_VOIP_VERSION_TRIAL
#endif

#if APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE < WECHAT_VOIP_VERSION_RELEASE || \
    APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE > WECHAT_VOIP_VERSION_TRIAL
#error "APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE must be 0 (release), 1 (development), or 2 (trial)"
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_DEBUG_LOG
#define APP_CONFIG_WECHAT_VOIP_DEBUG_LOG 0
#endif

#define WECHAT_VOIP_DEVICE_API_BASE APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE
#define WECHAT_VOIP_API_BASE APP_CONFIG_WECHAT_VOIP_API_BASE
#define WECHAT_VOIP_MQTT_URI APP_CONFIG_WECHAT_VOIP_MQTT_URI
#define WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE
#define WECHAT_VOIP_DEBUG_LOG APP_CONFIG_WECHAT_VOIP_DEBUG_LOG
