#pragma once

#include "sdkconfig.h"

#include "app_config.h"

#ifndef APP_CONFIG_WECHAT_VOIP_ENABLE
#define APP_CONFIG_WECHAT_VOIP_ENABLE 1
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE
#define APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE APP_CONFIG_DEVICE_BINDING_API_BASE
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_API_BASE
#define APP_CONFIG_WECHAT_VOIP_API_BASE APP_CONFIG_DEVICE_BINDING_API_BASE
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_MQTT_URI
#define APP_CONFIG_WECHAT_VOIP_MQTT_URI APP_CONFIG_DEVICE_BINDING_MQTT_URI
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE
#define APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE 1
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_DEBUG_LOG
#define APP_CONFIG_WECHAT_VOIP_DEBUG_LOG 0
#endif

/*
 * Device display capabilities reported to ThingConnect. Keep these separate
 * from the codec target below: changing the camera bitrate or encode size must
 * not silently turn the physical 480x320 panel into a portrait device.
 */
#ifndef APP_CONFIG_WECHAT_VOIP_SCREEN_WIDTH
#define APP_CONFIG_WECHAT_VOIP_SCREEN_WIDTH 480
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_SCREEN_HEIGHT
#define APP_CONFIG_WECHAT_VOIP_SCREEN_HEIGHT 320
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_CAMERA_ROTATION
/* Protocol UI metadata only: WeChat rotates the published camera view.
 * Keep the local YUV420 -> H264 frame path byte-for-byte unchanged. */
#define APP_CONFIG_WECHAT_VOIP_CAMERA_ROTATION 180
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_OBJECT_FIT
/*
 * ThingConnect accepts only "fill" or "contain" for this protocol field.
 * Preserve the remote picture aspect ratio here; the local renderer applies
 * its own centered cover crop independently.
 */
#define APP_CONFIG_WECHAT_VOIP_OBJECT_FIT "contain"
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_VIDEO_WIDTH
#define APP_CONFIG_WECHAT_VOIP_VIDEO_WIDTH CONFIG_APP_DEVICE_CALL_VIDEO_WIDTH
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_VIDEO_HEIGHT
#define APP_CONFIG_WECHAT_VOIP_VIDEO_HEIGHT CONFIG_APP_DEVICE_CALL_VIDEO_HEIGHT
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_UP_VIDEO_MEDIA
#define APP_CONFIG_WECHAT_VOIP_UP_VIDEO_MEDIA "h264"
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_DOWN_VIDEO_MEDIA
#define APP_CONFIG_WECHAT_VOIP_DOWN_VIDEO_MEDIA "mjpeg"
#endif

#define WECHAT_VOIP_DEVICE_API_BASE APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE
#define WECHAT_VOIP_API_BASE APP_CONFIG_WECHAT_VOIP_API_BASE
#define WECHAT_VOIP_MQTT_URI APP_CONFIG_WECHAT_VOIP_MQTT_URI
#define WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE
#define WECHAT_VOIP_DEBUG_LOG APP_CONFIG_WECHAT_VOIP_DEBUG_LOG
#define WECHAT_VOIP_LOCAL_VIDEO_ENABLE APP_CONFIG_WECHAT_VOIP_LOCAL_VIDEO_ENABLE
#define WECHAT_VOIP_REMOTE_VIDEO_ENABLE CONFIG_APP_WECHAT_VOIP_REMOTE_VIDEO_ENABLE
#define WECHAT_VOIP_SCREEN_WIDTH APP_CONFIG_WECHAT_VOIP_SCREEN_WIDTH
#define WECHAT_VOIP_SCREEN_HEIGHT APP_CONFIG_WECHAT_VOIP_SCREEN_HEIGHT
#define WECHAT_VOIP_CAMERA_ROTATION APP_CONFIG_WECHAT_VOIP_CAMERA_ROTATION
#define WECHAT_VOIP_OBJECT_FIT APP_CONFIG_WECHAT_VOIP_OBJECT_FIT
#define WECHAT_VOIP_VIDEO_WIDTH APP_CONFIG_WECHAT_VOIP_VIDEO_WIDTH
#define WECHAT_VOIP_VIDEO_HEIGHT APP_CONFIG_WECHAT_VOIP_VIDEO_HEIGHT
#define WECHAT_VOIP_UP_VIDEO_MEDIA APP_CONFIG_WECHAT_VOIP_UP_VIDEO_MEDIA
#define WECHAT_VOIP_DOWN_VIDEO_MEDIA APP_CONFIG_WECHAT_VOIP_DOWN_VIDEO_MEDIA
