ifeq ($(CONFIG_APPLICATION_TIRTC_DEMO),y)
ccflags-y += -Iapplication/app_tirtc_demo/include
ccflags-y += -Iapplication/com_services/audio/cap/include
ccflags-y += -Iapplication/com_services/audio/player/include
ccflags-y += -Iapplication/com_services/video/include
endif

src-$(CONFIG_APPLICATION_TIRTC_DEMO) += src/tirtc_demo_app.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += src/tirtc_demo_cloud.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += src/tirtc_demo_media.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += src/tirtc_demo_platform.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += src/tirtc_demo_sdk_gate.c
src-$(CONFIG_APPLICATION_TIRTC_SCREEN_DEBUG) += debug/tirtc_screen_debug.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += ui/ui_tirtc_demo.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += ui/tirtc_demo_embedded_assets.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += ui/ai_chat_avatar_assets.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += ui/lv_font_tirtc_s3_18.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += ui/text_assets.c
src-$(CONFIG_APPLICATION_TIRTC_DEMO) += ui/tirtc_demo_s3_text_extra.c
