#!/usr/bin/env python3
"""Generate image masks for fixed G32 CJK copy missing from the S3 runtime atlas.

The S3 device source atlas remains the primary lookup table. This generator
only fills fixed strings introduced by the G32 integration so they never fall
back to the Junzheng runtime font. Pass ui_tirtc_demo_pixel.h as --ui-source;
whole-screen screenshots and the legacy non-pixel UI are deliberately excluded.
"""

from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


SIZES = (10, 12, 16)


def c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def c_string_literals(source: str) -> list[str]:
    values: list[str] = []
    for match in re.finditer(r'"(?:\\.|[^"\\])*"', source):
        try:
            value = ast.literal_eval(match.group(0))
        except (SyntaxError, ValueError):
            continue
        if re.search(r"[\u4e00-\u9fff]", value) and value not in values:
            values.append(value)
    return values


def base_asset_strings(source: str) -> set[str]:
    values: set[str] = set()
    pattern = re.compile(r'\{"((?:\\.|[^"\\])*)",\s*(?:10|12|16),')
    for match in pattern.finditer(source):
        try:
            values.add(ast.literal_eval(f'"{match.group(1)}"'))
        except (SyntaxError, ValueError):
            continue
    return values


def rasterize(text: str, size: int, font_path: Path) -> tuple[int, int, list[int]]:
    font = ImageFont.truetype(str(font_path), size=size)
    probe = Image.new("L", (1, 1), 0)
    draw = ImageDraw.Draw(probe)
    bbox = draw.multiline_textbbox((0, 0), text, font=font, spacing=2)
    width = max(1, bbox[2] - bbox[0])
    height = max(1, bbox[3] - bbox[1])
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    draw.multiline_text((-bbox[0], -bbox[1]), text, font=font, fill=255, spacing=2)
    if hasattr(image, "get_flattened_data"):
        pixels = list(image.get_flattened_data())
    else:
        pixels = list(image.getdata())
    return width, height, pixels


def write_header(path: Path) -> None:
    path.write_text(
        """#ifndef _TIRTC_DEMO_S3_TEXT_EXTRA_H
#define _TIRTC_DEMO_S3_TEXT_EXTRA_H

#include "text_assets.h"

const ui_text_asset_t *ui_g32_text_asset_find(const char *text, uint8_t size);
extern const size_t ui_g32_text_asset_count;

#endif
""",
        encoding="utf-8",
        newline="\n",
    )


def write_source(path: Path, strings: list[str], font_path: Path) -> None:
    lines = [
        "/* Generated by tools/generate_g32_s3_text_images.py. */",
        '#include "tirtc_demo_s3_text_extra.h"',
        "",
    ]
    entries: list[str] = []
    for index, text in enumerate(strings):
        for size in SIZES:
            width, height, pixels = rasterize(text, size, font_path)
            map_name = f"ui_g32_text_{index:03d}_{size}_map"
            image_name = f"ui_g32_text_{index:03d}_{size}_img"
            lines.append(
                "static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST "
                f"uint8_t {map_name}[] = {{"
            )
            for offset in range(0, len(pixels), 16):
                chunk = ", ".join(f"0x{value:02x}" for value in pixels[offset : offset + 16])
                lines.append(f"    {chunk},")
            lines.extend(
                [
                    "};",
                    "",
                    f"static const lv_img_dsc_t {image_name} = {{",
                    "    .header.cf = LV_IMG_CF_ALPHA_8BIT,",
                    "    .header.always_zero = 0,",
                    "    .header.reserved = 0,",
                    f"    .header.w = {width},",
                    f"    .header.h = {height},",
                    f"    .data_size = {width} * {height},",
                    f"    .data = {map_name},",
                    "};",
                    "",
                ]
            )
            entries.append(
                f'    {{"{c_escape(text)}", {size}, 0, 2, &{image_name}}},'
            )

    lines.append("static const ui_text_asset_t s_g32_text_assets[] = {")
    lines.extend(entries)
    lines.extend(
        [
            "};",
            "",
            "const size_t ui_g32_text_asset_count =",
            "    sizeof(s_g32_text_assets) / sizeof(s_g32_text_assets[0]);",
            "",
            "const ui_text_asset_t *ui_g32_text_asset_find(const char *text, uint8_t size)",
            "{",
            "    uint8_t normalized;",
            "",
            "    if (text == NULL || text[0] == '\\0') {",
            "        return NULL;",
            "    }",
            "    normalized = ui_text_asset_normalize_size(size);",
            "    for (size_t i = ui_g32_text_asset_count; i > 0U; --i) {",
            "        const ui_text_asset_t *asset = &s_g32_text_assets[i - 1U];",
            "",
            "        if (asset->size == normalized && strcmp(asset->text, text) == 0) {",
            "            return asset;",
            "        }",
            "    }",
            "    return NULL;",
            "}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ui-source", type=Path, required=True)
    parser.add_argument("--base-assets", type=Path, required=True)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--output-c", type=Path, required=True)
    parser.add_argument("--output-h", type=Path, required=True)
    args = parser.parse_args()

    ui_strings = c_string_literals(args.ui_source.read_text(encoding="utf-8"))
    base_strings = base_asset_strings(args.base_assets.read_text(encoding="utf-8"))
    extra_strings = [value for value in ui_strings if value not in base_strings]

    args.output_c.parent.mkdir(parents=True, exist_ok=True)
    args.output_h.parent.mkdir(parents=True, exist_ok=True)
    write_source(args.output_c, extra_strings, args.font)
    write_header(args.output_h)
    print(f"S3 base strings: {len(base_strings)}")
    print(f"G32 fixed CJK strings: {len(ui_strings)}")
    print(f"Generated G32-only text images: {len(extra_strings)} x {len(SIZES)}")


if __name__ == "__main__":
    main()
