#ifndef TIRTC_LINK_DEFAULTS_H
#define TIRTC_LINK_DEFAULTS_H

/*
 * Optional settings use defaults here so an existing local credential file
 * does not need to be replaced whenever a new tuning knob is introduced.
 * Product projects may override any value before including this header.
 */
#ifndef TIRTC_LINK_ENABLE_SAMPLE_MEDIA
#define TIRTC_LINK_ENABLE_SAMPLE_MEDIA 1
#endif

#ifndef TIRTC_LINK_AUTO_CONNECT
#define TIRTC_LINK_AUTO_CONNECT 0
#endif

#ifndef TIRTC_LINK_SERVICE_ENDPOINT
#define TIRTC_LINK_SERVICE_ENDPOINT ""
#endif

#ifndef TIRTC_LINK_ENABLE_CONNECT_CACHE
#define TIRTC_LINK_ENABLE_CONNECT_CACHE 1
#endif

#ifndef TIRTC_LINK_REMOTE_DEVICE_ID
#define TIRTC_LINK_REMOTE_DEVICE_ID ""
#endif

#ifndef TIRTC_LINK_REMOTE_TOKEN
#define TIRTC_LINK_REMOTE_TOKEN ""
#endif

#ifndef TIRTC_LINK_MAX_SEND_BUFFER
#define TIRTC_LINK_MAX_SEND_BUFFER (128U * 1024U)
#endif

#ifndef TIRTC_LINK_SAMPLE_AUTO_PUBLISH
#define TIRTC_LINK_SAMPLE_AUTO_PUBLISH 1
#endif

#ifndef TIRTC_LINK_SAMPLE_VIDEO_STREAM_ID
#define TIRTC_LINK_SAMPLE_VIDEO_STREAM_ID 11U
#endif

#ifndef TIRTC_LINK_SAMPLE_AUDIO_STREAM_ID
#define TIRTC_LINK_SAMPLE_AUDIO_STREAM_ID 10U
#endif

#ifndef TIRTC_LINK_SAMPLE_START_DELAY_MS
#define TIRTC_LINK_SAMPLE_START_DELAY_MS 700U
#endif

#ifndef TIRTC_LINK_SAMPLE_AUDIO_PACKET_MS
#define TIRTC_LINK_SAMPLE_AUDIO_PACKET_MS 20U
#endif

#ifndef TIRTC_LINK_SAMPLE_VIDEO_BUFFER_PERCENT
#define TIRTC_LINK_SAMPLE_VIDEO_BUFFER_PERCENT 80U
#endif

#ifndef TIRTC_LINK_SAMPLE_AUDIO_BUFFER_PERCENT
#define TIRTC_LINK_SAMPLE_AUDIO_BUFFER_PERCENT 95U
#endif

#ifndef TIRTC_LINK_SDK_LOG_LEVEL
#define TIRTC_LINK_SDK_LOG_LEVEL 2
#endif

#ifndef TIRTC_LINK_STATUS_LOG_INTERVAL_MS
#define TIRTC_LINK_STATUS_LOG_INTERVAL_MS 30000U
#endif

#ifndef TIRTC_LINK_WIFI_JOIN_DELAY_MS
#define TIRTC_LINK_WIFI_JOIN_DELAY_MS 2000U
#endif

#ifndef TIRTC_LINK_WIFI_RETRY_MS
#define TIRTC_LINK_WIFI_RETRY_MS 10000U
#endif

#ifndef TIRTC_LINK_NTP_TIMEOUT_MS
#define TIRTC_LINK_NTP_TIMEOUT_MS 5000U
#endif

#ifndef TIRTC_LINK_NTP_RETRY_MS
#define TIRTC_LINK_NTP_RETRY_MS 30000U
#endif

#ifndef TIRTC_LINK_START_RETRY_MS
#define TIRTC_LINK_START_RETRY_MS 10000U
#endif

#ifndef TIRTC_LINK_WORKER_STACK_BYTES
#define TIRTC_LINK_WORKER_STACK_BYTES 12288U
#endif

#ifndef TIRTC_LINK_WORKER_POLL_MS
#define TIRTC_LINK_WORKER_POLL_MS 250U
#endif

#ifndef TIRTC_LINK_SAMPLE_WORKER_STACK_BYTES
#define TIRTC_LINK_SAMPLE_WORKER_STACK_BYTES 6144U
#endif

#ifndef TIRTC_LINK_SAMPLE_WORKER_POLL_MS
#define TIRTC_LINK_SAMPLE_WORKER_POLL_MS 10U
#endif

#ifndef TIRTC_LINK_REMOTE_DEVICE_ID_MAX
#define TIRTC_LINK_REMOTE_DEVICE_ID_MAX 128U
#endif

#ifndef TIRTC_LINK_REMOTE_TOKEN_MAX
#define TIRTC_LINK_REMOTE_TOKEN_MAX 2048U
#endif

#ifndef TIRTC_LINK_DISCONNECT_QUEUE_DEPTH
#define TIRTC_LINK_DISCONNECT_QUEUE_DEPTH 3U
#endif

#if TIRTC_LINK_ENABLE_SAMPLE_MEDIA != 0 && TIRTC_LINK_ENABLE_SAMPLE_MEDIA != 1
#error "TIRTC_LINK_ENABLE_SAMPLE_MEDIA must be 0 or 1"
#endif
#if TIRTC_LINK_AUTO_CONNECT != 0 && TIRTC_LINK_AUTO_CONNECT != 1
#error "TIRTC_LINK_AUTO_CONNECT must be 0 or 1"
#endif
#if TIRTC_LINK_ENABLE_CONNECT_CACHE != 0 && \
    TIRTC_LINK_ENABLE_CONNECT_CACHE != 1
#error "TIRTC_LINK_ENABLE_CONNECT_CACHE must be 0 or 1"
#endif
#if TIRTC_LINK_SAMPLE_AUTO_PUBLISH != 0 && TIRTC_LINK_SAMPLE_AUTO_PUBLISH != 1
#error "TIRTC_LINK_SAMPLE_AUTO_PUBLISH must be 0 or 1"
#endif
#if TIRTC_LINK_SAMPLE_VIDEO_STREAM_ID > 15U || \
    TIRTC_LINK_SAMPLE_AUDIO_STREAM_ID > 15U || \
    TIRTC_LINK_SAMPLE_VIDEO_STREAM_ID == TIRTC_LINK_SAMPLE_AUDIO_STREAM_ID
#error "Sample audio/video stream IDs must be different values in range 0..15"
#endif
#if TIRTC_LINK_SAMPLE_AUDIO_PACKET_MS == 0U || \
    TIRTC_LINK_SAMPLE_AUDIO_PACKET_MS > 100U
#error "TIRTC_LINK_SAMPLE_AUDIO_PACKET_MS must be in range 1..100"
#endif
#if TIRTC_LINK_SAMPLE_VIDEO_BUFFER_PERCENT == 0U || \
    TIRTC_LINK_SAMPLE_VIDEO_BUFFER_PERCENT > 100U || \
    TIRTC_LINK_SAMPLE_AUDIO_BUFFER_PERCENT == 0U || \
    TIRTC_LINK_SAMPLE_AUDIO_BUFFER_PERCENT > 100U
#error "Sample buffer thresholds must be in range 1..100"
#endif
#if TIRTC_LINK_SDK_LOG_LEVEL < 1 || TIRTC_LINK_SDK_LOG_LEVEL > 5
#error "TIRTC_LINK_SDK_LOG_LEVEL must be in range 1..5"
#endif
#if TIRTC_LINK_WIFI_RETRY_MS == 0U || TIRTC_LINK_NTP_TIMEOUT_MS == 0U || \
    TIRTC_LINK_NTP_RETRY_MS == 0U || TIRTC_LINK_START_RETRY_MS == 0U || \
    TIRTC_LINK_WORKER_POLL_MS == 0U || \
    TIRTC_LINK_SAMPLE_WORKER_POLL_MS == 0U
#error "Retry, timeout and worker poll intervals must be non-zero"
#endif
#if TIRTC_LINK_WORKER_STACK_BYTES < 4096U || \
    TIRTC_LINK_SAMPLE_WORKER_STACK_BYTES < 4096U
#error "Worker stacks smaller than 4096 bytes are not supported by this demo"
#endif
#if TIRTC_LINK_REMOTE_DEVICE_ID_MAX < 2U || \
    TIRTC_LINK_REMOTE_TOKEN_MAX < 2U || \
    TIRTC_LINK_DISCONNECT_QUEUE_DEPTH == 0U
#error "Connection storage limits are too small"
#endif
#if TIRTC_LINK_MAX_SEND_BUFFER < (32U * 1024U)
#error "TIRTC_LINK_MAX_SEND_BUFFER is too small for the delivered JPEG asset"
#endif

#endif
