#pragma once

#include <stdint.h>

#include "freertos/FreeRTOS.h"

#define TIRTC_SESSION_CONTROL_EVENT_WAIT_TICKS  pdMS_TO_TICKS(20)
#define TIRTC_SESSION_TEARDOWN_EVENT_WAIT_TICKS pdMS_TO_TICKS(100)

#define TIRTC_SESSION_WORKER_TASK_STACK    (64 * 1024)
#define TIRTC_SESSION_WORKER_TASK_PRIORITY 3
#define TIRTC_SESSION_WORKER_POLL_MS       100U
#define TIRTC_SESSION_TEARDOWN_TASK_STACK  (16 * 1024)
#define TIRTC_SESSION_TEARDOWN_TASK_PRIORITY (TIRTC_SESSION_WORKER_TASK_PRIORITY + 1)
#define TIRTC_SESSION_SDK_API_LOCK_WAIT_MS 500U
#define TIRTC_SESSION_SDK_API_LOCK_WAIT_TICKS pdMS_TO_TICKS(TIRTC_SESSION_SDK_API_LOCK_WAIT_MS)

#define TIRTC_SESSION_VIDEO_TX_QUEUE_LEN                8
#define TIRTC_SESSION_VIDEO_TX_BUFFER_POOL_SIZE         (TIRTC_SESSION_VIDEO_TX_QUEUE_LEN + 2)
#define TIRTC_SESSION_VIDEO_TX_BUFFER_SLOT_INVALID      UINT8_MAX
#define TIRTC_SESSION_VIDEO_TX_TASK_STACK               (12 * 1024)
#define TIRTC_SESSION_VIDEO_TX_TASK_PRIORITY            11
#define TIRTC_SESSION_AUDIO_TX_QUEUE_LEN                16
#define TIRTC_SESSION_AUDIO_TX_TARGET_BACKLOG           8
#define TIRTC_SESSION_AUDIO_TX_TASK_STACK               (10 * 1024)
#define TIRTC_SESSION_AUDIO_TX_TASK_PRIORITY            12
#define TIRTC_SESSION_AUDIO_TX_MAX_AGE_US               400000ULL

#define TIRTC_SESSION_ENABLE_TIME_STREAM_MESSAGES       0
#define TIRTC_SESSION_TIME_MESSAGE_INITIAL_DELAY_US     250000ULL
#define TIRTC_SESSION_TIME_MESSAGE_RETRY_DELAY_US       50000ULL
#define TIRTC_SESSION_TIME_MESSAGE_PERIOD_US            10000000ULL

#define TIRTC_SESSION_DEFERRED_FULL_RESET_DELAY_US      200000ULL
#define TIRTC_SESSION_RESTART_AFTER_FULL_RESET_DELAY_US 300000ULL
#define TIRTC_SESSION_SDK_RESTART_SETTLE_US             1500000ULL
#define TIRTC_SESSION_MEDIA_BOOTSTRAP_INITIAL_DELAY_US  5000ULL
#define TIRTC_SESSION_MEDIA_BOOTSTRAP_RETRY_DELAY_US    5000ULL
#define TIRTC_SESSION_MEDIA_AUDIO_FOLLOWUP_DELAY_US     10000ULL
#define TIRTC_SESSION_INVALID_HANDLE_GRACE_US           1500000ULL
#define TIRTC_SESSION_TEST_MEDIA_WARMUP_US              80000ULL
#define TIRTC_SESSION_TEST_MEDIA_RETRY_DELAY_US         40000ULL
#define TIRTC_SESSION_DISCONNECT_TIMEOUT_US             3000000ULL
#define TIRTC_SESSION_START_RETRY_DELAY_US              10000000ULL
#define TIRTC_SESSION_STOP_WAIT_MS                      1000U

#define TIRTC_SESSION_SDK_LOG_LEVEL                     0
#define TIRTC_SESSION_WEBRTC_LOG_LEVEL                  (TIRTC_SESSION_SDK_LOG_LEVEL > 10 ? (TIRTC_SESSION_SDK_LOG_LEVEL - 10) : 0)
#define TIRTC_SESSION_SDK_LOG_CHUNK_LEN                 160

#define TIRTC_SESSION_CONN_USER_MAGIC                   0x52544353U
#define TIRTC_SESSION_MAX_SEND_BUFFER                   (512U * 1024U)
#define TIRTC_SESSION_SEND_BUFFER_WARN_PCT              60U
#define TIRTC_SESSION_SEND_BUFFER_DROP_PCT              85U
#define TIRTC_SESSION_SEND_BUFFER_LOG_PERIOD_MS         1000U
